### PR TITLE
Feature/usage add missing opt

### PR DESCRIPTION
**Pull request by bobsaintcool**
Add 3 options into the helper output provided by `-h`/`--help`.

### CODE REVIEW

**Comment by emersion** [comment]
Seems like commits from another PR have sneaked in. You can probably drop them by doing `git rebase -i master`.

**Comment by emersion** [comment]
Still needs rebase

**Comment by bobsaintcool** [comment]
This should be addressed by 6a824dc81ac9659f15a141a660e1aacefb2ae0d3

**Comment by emersion** [comment]
Thanks!

**Comment by bobsaintcool** [comment]
Thanks for your time on the review.

**Pull request merged**
