### PR TITLE
. is included in link when followed

### PR DESCRIPTION
**Pull request by morten-b**

### CODE REVIEW

**Comment by emersion** [comment]
Hmm. I'd say this is a terminal emulator bug.

**Comment by morten-b** [comment]
As far as I can tell a trailing dot is a valid adress, so the terminal emulator have no way of knowing if it is part of the link or the language syntax.

See this: http://www.dns-sd.org/TrailingDotsInDomainNames.html

**Comment by emersion** [comment]
I guess the real solution would be to add support for this in `scdoc`. Opened https://todo.sr.ht/~sircmpwn/scdoc/25

**Comment by morten-b** [comment]
Excellent. Should we close this?

**Pull request closed without merging**
