### PR TITLE
Use frame scheduling when drawing frames

### PR DESCRIPTION
**Pull request by emersion**
This synchronizes rendering with the vsync. This should fix "no buffer
available" errors.

Fixes https://github.com/emersion/mako/issues/70

### CODE REVIEW

**Comment by emersion** [comment]
This build failure is weird. Probably a pango bug.

**Comment by emersion** [comment]
>I pulled this down to play with it and I get a segfault when receiving a notification

Fixed

**Comment by vilhalmer** [comment]
LGTM!

**Comment by vilhalmer** [comment]
Thanks!

**Pull request merged**
