### PR TITLE
No blur

### LINKED ISSUE #387: Blurry notification/Hi-DPI
Using mako i got very strange behaviour: all the time i receive notifications, first notification gets blurry, but reloading sway/using slurp/getting another notification and all the notifications are no longer blurry.
20211006_04h18m49s_grim
20211006_04h19m00s_grim

I'm using a Hi-DPI laptop, and of course with `output eDP-1 scale 1` everything works fine.

### PR DESCRIPTION
**Pull request by lilydjwg**
This should fix #387.

### CODE REVIEW

**Comment by lilydjwg** [comment]
The CI failure seems to be unrelated, complaining a build option I didn't touch.

**Review by WhyNotHugo — APPROVED** [review]
Works for me. Thanks!

**Comment by kabouzeid** [comment]
Works for me too, thanks for the PR! Hoping this will get merged soon :)

**Comment by jplatte** [comment]
Ping @emersion

**Comment by WhyNotHugo** [comment]
The issue has been less problematic lately; the first notification is only blurry for an instant and then it quickly unblurs. I think this has been [partially/mostly] fixed.

This PR has conflicts now tho.

**Comment by lilydjwg** [comment]
I've removed all other commits and rebased the de-flickering commit on master.

**Comment by emersion** [comment]
This commit doesn't make sense to me. It works fine when there is only one screen, but breaks as soon as there are multiple.

**Comment by lilydjwg** [comment]
Oops. I'll try to fix it when I get access to my other screen.

**Comment by emersion** [comment]
I don't think it's possible to fix without a Sway change to send the `wl_surface.enter` event before the layer-surface is mapped.

**Comment by lilydjwg** [comment]
Hi, I rebased my commit and tested it on my setup. Yes it would be nicer if we could receive an enter enter before the surface is mapped, but I think this is a good-enough workaround for me.

I have two monitors, one is the laptop's internal screen and the other is an external 4K monitor. I mostly work on the external one while I put some informational windows on the laptop's one, so for the most of time notifications will appear on the external one, i.e. it doesn't switch between multiple outputs.

The issue I have is that, the first frame of mako is not only blurry but also has a different size (it seems to be accumulated difference of text height). This patch makes it not "jump" when it re-appears on the same output.

**Pull request closed without merging**
