### PR TITLE
nonexistent replaces_id

### PR DESCRIPTION
**Pull request by TheEdward162**
Referencing #167

### CODE REVIEW

**Comment by TheEdward162** [comment]
The usecase is that I have a volume notification script that runs `notfiy-send.sh -r 8000 Volume $volume` when the volume changes. I'd like to avoid having to store the returned id in a temporary file, plus the spec doesn't exactly consider this case, so I think this is the best thing to do user experience-wise. Either way, `mako` returns a new ID for non-existent `replaces_id` even if the `replaces_id < new_id`, which is kind of weird. If the user misses the replace notification by just a moment, a different ID is generated, which brings us back to temporary files.

Right now on `dunst` this only ever uses notification with id 8000 for this command, even if one doesn't exist yet. It doesn't, however, remove the replace-created ID from the pool of natural IDs. This seems to work well enough anyway.

> increment the new ID until there's no existing notification with such an ID.

I don't understand what you mean by this. Old notifications (even the replaced ones) are deleted and their IDs are forgotten. I added the primitive hashset to skip IDs which were replace-created in natural ID generation so we don't run into cases where you get a naturally generated notification with the same ID as one that was replace-created previously.

**Comment by vilhalmer** [comment]
I used to feel that the temp files were kind of a hack as well, but if you store them in tmpfs they never really exist anyway.

>Right now on dunst this only ever uses notification with id 8000 for this command, even if one doesn't exist yet. It doesn't, however, remove the replace-created ID from the pool of natural IDs. This seems to work well enough anyway.

If dunst isn't doing anything special about the id, I'd much rather follow its example than add an entire new data structure to store one or two integers.

>increment the new ID until there's no existing notification with such an ID.

I think @emersion means that when we see a new incoming notification without a `replaces_id` (i.e. most of them), iterate through any notifications that happen to exist at the time and make sure the newly assigned id is higher than any of them. This might skip some ids, but we don't actually care that they're contiguous. In your case this would mean when the first notification comes in while the volume display is open, assigned ids will jump from something low to 8001 and then continue counting.

**Comment by emersion** [comment]
We could also go through all notifications and pick the lowest unused ID.

**Comment by TheEdward162** [comment]
Okay, I'll remove the hashset.

> iterate through any notifications that happen to exist at the time and make sure the newly assigned id is higher than any of them.

I think this can easily lead to integer overflow if someone requests MAXINT as `replaces_id`.

> We could also go through all notifications and pick the lowest unused ID.

ID reuse in non-replace notifications is disallowed by the spec, unless overflow happens.

**Comment by vilhalmer** [comment]
>I think this can easily lead to integer overflow if someone requests MAXINT as replaces_id.

The fact that there is so much nuance to this is leading me back to thinking it’s not worth allowing arbitrary ids to be chosen. Missing the notification you’re replacing isn’t really a problem, since you still achieve the goal of not having two on screen at once. Needing to store the id somewhere is not really not that surprising of a requirement given that you’re trying to interact with a stateful daemon, it just happens that `notify-send` has no way of doing it internally since it is short-lived. Allowing an external tool to dictate the value of what is supposed to be an internal tracking mechanism seems like it can only ever lead to bugs or weird edges.

**Comment by TheEdward162** [comment]
As soon as the id is given to the user and encouraged to be used as an identifier I don't think it can be called internal anymore. The tracking wouldn't be needed at all if there was no external `replaces_id`.

If you want to avoid the complexity of the hashset, I would still propose to at least do what `dunst` does and improve the quality of UX even if it can potentially lead to a small window of time where there are two notifications with the same id.

Plus the idea of using the lowest currently unused ID only needs one addition to adhere to the spec - start the search from `new_id` upwards.

**Comment by emersion** [comment]
I agree with @vilhalmer: that the use-case you describe (using a hardcoded ID) seems harmful to support. I don't want to encourage people to do this, the API was never intended to be used this way.

It seems like dunst offers another API for this: `set_stack_tag`. The name is a little misleading.

> The stack tag can be set by the client with the 'synchronous', 'private-synchronous' 'x-canonical-private-synchronous' or the 'x-dunst-stack-tag' hints.

**Comment by TheEdward162** [comment]
Well okay, if you consider improving user experience harmful, I'll close the issue. I don't think we can make any assumptions on how the API was designed to be used since it doesn't fully explain what to do in this case.

**Comment by emersion** [comment]
I think it's pretty clear from the name that you're only supposed to provide `replace_id` if you have a handle to an existing notification.

>Well okay, if you consider improving user experience harmful, I'll close the issue

I'm not against adding another way to improve UX, with something similar to dunst's solution.

**Comment by TheEdward162** [comment]
I'm confused now. Can you please tell me exactly which of the proposed solutions are you least opposed to? 

I'm happy to implement any of them, but I though it would be best to improve on the dunst solution by not allowing natural ID notfications to mix with the replace-created ones. Normally this would be an issue of using the stdlib HashSet, but since the project is in C and I didn't want to add a dependency on something random, I just added a very primitive implementation of a u32 HashSet.

Just to reiterate, the current patch solves all of the discussed issues - at the cost of added complexity. If you wouldn't be opposed to adding a dependency on some collections library (I don't really know C libraries), maybe that could be a better solution?

Lastly, the spec says "If replaces_id is not 0, the returned value is the same value as replaces_id.". This statement is on a separate line and clearly separated from the actual function of `replaces_id`. This leads me to believe that the semantical meaning of the name `replaces_id` really doesn't have much to do with the statement as a separate point. That is, if we were to adhere to this single line as a separate rule, it would mean that even if `replaces_id` was an non-existent id, we would still be obligated to return the same number (even if we chose not to actually display a new notification).

**Comment by emersion** [comment]
What I don't like about returning the replace_id even if the notification doesn't exist is that scripts use it to hardcode a particular ID. This causes issues because each script needs to use a unique ID, and there's no guarantee the replace_id isn't used by a regular notification (if you don't reboot your machine and get chat notifications, I suppose you can get to 8000 pretty quickly).

So an alternate solution is to use a string token. For instance, sending a notification with "brightness" will replace any notification previously submitted with the same string. Dunst calls this "stack tag".

**Comment by TheEdward162** [comment]
With the HashSet, that exact guarantee is upheld.

I agree that hardcoding values might be hard to keep track of, but that's up to the user, not mako as a deamon. (I'd like to use network ports as an analogy).

I don't know about stact tags. Are they part of the specification in any way, or will I need a separate notification sending tool?

**Comment by emersion** [comment]
>With the HashSet, that exact guarantee is upheld.

How so?

>I agree that hardcoding values might be hard to keep track of, but that's up to the user, not mako as a deamon. (I'd like to use network ports as an analogy).

I disagree. Network ports are a poor analogy because (1) all servers are generally always running as daemons (2) when you try to use both at the same time you have a clear error. 

>I don't know about stact tags. Are they part of the specification in any way, or will I need a separate notification sending tool?

It's a hint. If you use `notify-send`, these can be specified with `-h`.

**Comment by TheEdward162** [comment]
Because replace-created IDs are stored in the HashSet and are skipped in the natural ID selection process.

**Comment by emersion** [comment]
Let's say a normal notification has ID 8000, and your script uses a hardcoded 8000 replace_id. Your script will incorrectly replace the notification.

**Comment by TheEdward162** [comment]
That could happen even if mako didn't support this.

**Comment by emersion** [comment]
>That could happen even if mako didn't support this.

Yeah. Which is the reason why I don't want to support this use-case.

>I would argue that that's not as much of a mako problem as a user problem?

The issue here is that you're asking mako to explicitly support broken scripts.

**Comment by TheEdward162** [comment]
No, I'm asking to let the user decide what is broken and what is not, because one person is not a judge of what people find broken.

**Comment by emersion** [comment]
Sorry, this is not how it works. You're free to have a local patch if you want.

However as a maintainer I want to have the freedom to say no to a patch. Consider the maintainer: https://youtu.be/W2AR1owg0ao?t=1120

**Comment by TheEdward162** [comment]
I'm not forcing you to do anything. If you say no then that means no. The PR and issue are closed already.

**Comment by apprehensions** [comment]
#510 Depends on this, Please merge this.

**Comment by apprehensions** [comment]
fnott supports this, why can't mako?

**Comment by apprehensions** [comment]
> The optional notification ID that this notification replaces. **The server must atomically (ie with no flicker or other visual cues) replace the given notification with this one.**

Does mako not go by the specification? it says here the replaceid is exactly for the purpose that this PR intends to create, why was it wrongly rejected?

**Comment by emersion** [comment]
Please avoid spamming pull requests.

mako behaves like the spec says. There is a "tag" mechanism you can use instead for scripts.

**Pull request closed without merging**
